version: '3'
services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: ${process.env.INSTANCE_CONNECTION_NAME}
      DATABASE_PORT: 3306
      DATABASE_NAME: ${process.env.DATABASE_NAME}
      DATABASE_USERNAME: ${process.env.DATABASE_USERNAME}
      DATABASE_PASSWORD: ${process.env.DATABASE_PASSWORD}
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
