# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - emperia-strapi-e-retailer(Sephora-RO)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://emperiadev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3e181ff423d64289b58ebc7352f6fa9e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1c289331e65444a2b1e7722d63553d4d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: emperiadev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3e181ff423d64289b58ebc7352f6fa9e }}/emperiadev/emperiadev/emperiadev/strapi-demo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Sephora-RO'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'emperia-strapi-e-retailer'
        slot-name: 'Sephora-RO'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cd8d4c9917c345399a5a714331cb8bc6 }}
        images: 'emperiadev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3e181ff423d64289b58ebc7352f6fa9e }}/emperiadev/emperiadev/emperiadev/strapi-demo:${{ github.sha }}'